from typing import Protocol

from engine.models.node import Node
from engine.models.edge import Edge
from engine.models.document import Chunk, Document, EvidencePath

class GraphStore(Protocol):
    """Abstract port. KnowledgeGraph depends on this.

    project_id scoping: save_* methods rely on the object itself already
    carrying `project_id` (set by KnowledgeGraph before calling save_*).
    load_*/search methods take project_id explicitly.
    """

    # Nodes
    def save_node(self, node: Node) -> None: ...
    def load_nodes(self, project_id: str) -> dict[str, Node]: ...
    def delete_node(self, node_id: str) -> bool: ...

    # Edges
    def save_edge(self, edge: Edge) -> bool: ...
    def load_edges(self, project_id: str) -> list[Edge]: ...
    def get_edges_from(self, node_id: str) -> list[Edge]: ...
    def get_edges_to(self, node_id: str) -> list[Edge]: ...
    def get_edges_between(self, source_id: str, target_id: str) -> list[Edge]:...

    # Chunks
    def save_chunk(self, chunk: Chunk) -> None: ...
    def load_chunks(self, project_id: str) -> dict[str, Chunk]: ...
    def get_chunk(self, chunk_id: str) -> Chunk | None: ...

    # -- Documents --
    def save_document(self, doc: Document) -> None: ...
    def load_documents(self, project_id: str) -> dict[str, Document]: ...
    def get_document_by_checksum(self, checksum: str, project_id: str) -> Document | None: ...

    # -- Evidence --
    def save_evidence(self, ev: EvidencePath) -> str: ...
    def load_evidence_for_question(self, question: str, project_id: str, limit: int = 10) -> list[EvidencePath]: ...
    def get_evidence(self, evidence_id: str) -> EvidencePath | None: ...

    def close(self) -> None: ...